{% set name = "orch" %}
{% set version = "0.4.3" %}
{% set sha256 = "5267251f1b2c4786fe1cf597ef17eff134850c8177cbab4604e22119aa73ebd0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{name}}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - xonsh
    - xonda
    - pyyaml
    - lazyasd

test:
  imports:
    - orch 
  commands:
    - orch -h
about:
  home: http://github.com/xpdAcq/orch
  license: BSD-3-Clause 
  license_family: BSD 
  license_file: LICENSE
  summary: 'Dep installation orchestrator for complex builds on CI'

extra:
  recipe-maintainers:
    - CJ-Wright
