{% set name = "orch" %}
{% set version = "0.1.4" %}
{% set sha256 = "63858b5e615d0076dfb2ff1ae65a8031fd9f0781caf2c5086a82a232c65da1d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - xonsh
    - xonda
    - pyyaml
    - lazyasd

test:
  imports:
    - orch 
  commands:
    - orch -h
about:
  home: http://github.com/xpdAcq/orch
  license: BSD-3-Clause 
  license_family: BSD 
  license_file: LICENSE
  summary: 'Dep installation orchestrator for complex builds on CI'

extra:
  recipe-maintainers:
    - CJ-Wright
