{% set name = "orch" %}
{% set version = "0.2.0" %}
{% set sha256 = "b1e9dd1c0a1729ca3773c04c2329e817345bae34181042b6f19b794df3ac6752" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - xonsh
    - xonda
    - pyyaml
    - lazyasd

test:
  imports:
    - orch 
  commands:
    - orch -h
about:
  home: http://github.com/xpdAcq/orch
  license: BSD-3-Clause 
  license_family: BSD 
  license_file: LICENSE
  summary: 'Dep installation orchestrator for complex builds on CI'

extra:
  recipe-maintainers:
    - CJ-Wright
