travis:
  secure:
    BINSTAR_TOKEN: hklPBoVivBsZWh20rH1rdoAuanqFOigvQ26G/XiJWIsOQ5afYm5nbbhHHHbjwyord9++U8RxtUyXIBeq9gGQYzO1LCdYVfbNvgphPYcKmidwjS+5TwD537o6xnF5eT17p5QhwnM7wSXXa4KVNM7YBpl9aCicAmZP9SBk270/5o87oYD+Z1XQdBNQhd5Pdl089/BZY9qQ9PC6UDmJlBoLwbyRJZ6sSSB7fmPpVAOz5QPZfwRXD5QVrh20ckE6uDD/yp9bndhJn2FQMA5sMZoRmYa0vbxWCXtBVG67XDQ3bOLleIIi8SDK14zlSQXzTwcA7xZN51g+ofBrmDUa0hmot89bSjAugEXOQRnPqA8tHrz+/kJIyfODCkliSqB6MLokfDG5kjsWYOYtrv5UgAUtX6ISPehRpWZEf4rJvGvOLzeQwmivxEi0YAOF6xqsasZdcSBwOXdB9LZEOR3L45fcKvqkD+GFREI85ChkdScz6YSDljmlZ2yBY1r8Iw7CFaSZqcQsJ9DBGTiuUll8Y13ym7Nq2KQJ3fjLpnbJk/Ls5KS0D0GrfJBXHQgJwY0nDQduzfVhMtLekqwn+JnPY1nhZ2bCeMcsRzvX9wHDrD74YFCZ3TJ7sBfIG15vaFNYTsYE0fufz0fDo4nw8XBmrHtWVFV04KUefjWMTUP88l3C3qA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
